#!/bin/sh
#absolute path to your nvidia-cuda (nvcc) compiler

NVCC="/usr/local/cuda-12.2/bin/nvcc"
#your XX digit architecture in "-gencode arch=compute_XX,code=sm_XX"
FLAGS="-gencode arch=compute_61,code=sm_61"
#Lulesh Source directory
LuleshSourcePath="/home/tim/Studium/Alpaka_Project/alpaka/LULESH/cuda/src"



LuleshDestination="$LuleshSourcePath/build"
mkdir $LuleshDestination
$NVCC $FLAGS $LuleshSourcePath/lulesh.cu -I $LuleshSourcePath/ -c -o $LuleshDestination/lulesh.o
$NVCC $FLAGS $LuleshSourcePath/allocator.cu -I $LuleshSourcePath/ -c -o $LuleshDestination/allocator.o
$NVCC $FLAGS $LuleshSourcePath/lulesh-comms.cu -I $LuleshSourcePath/ -c -o $LuleshDestination/lulesh-comms.o
$NVCC $FLAGS $LuleshSourcePath/lulesh-comms-gpu.cu -I $LuleshSourcePath/ -c -o $LuleshDestination/lulesh-comms-gpu.o
$NVCC $FLAGS $LuleshDestination/allocator.o $LuleshDestination/lulesh.o $LuleshDestination/lulesh-comms.o $LuleshDestination/lulesh-comms-gpu.o -o $LuleshDestination/lulesh
rm -rf $LuleshDestination/allocator.o $LuleshDestination/lulesh-comms.o $LuleshDestination/lulesh-comms-gpu.o $LuleshDestination/lulesh.o
echo "\n\nexecute cd $LuleshDestination && ./lulesh -s 45 to run"
